### ISSUE TITLE
File /etc/dphys-swapfile does not exist.

### ISSUE THREAD

**Issue by An-and14** [CityofEdmonton/pedestrian-counter#42]
![Screenshot (86)](https://user-images.githubusercontent.com/31886555/59479645-1d105800-8ea1-11e9-949e-c3fd068711d0.png)

**Comment by LiyaoJiang1998** [comment]
Hi @An-and14 , this project is designed for Raspberry Pi 3B+, /etc/dphys-swapfile is some swapfile system Raspberry Pi uses. The hardware will be necessary for the program to run.

**Comment by LiyaoJiang1998** [comment]
#44 updated the README with instructions
