### ISSUE TITLE
Remove hard-coded paths

### ISSUE THREAD

**Issue by j-rewerts** [CityofEdmonton/pedestrian-counter#9]

**Comment by j-rewerts** [comment]
[Example](https://github.com/CityofEdmonton/pedestrian-counter/blob/503112a8f465b7ac534a38e0f82f082694103e41/start.sh#L3).

**Comment by j-rewerts** [comment]
Maybe just pass the path into the ./start.sh script as a variable

**Comment by kylecjo** [comment]
done #12
